config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  resources :stages
  resources :tasks
  resources :customers
  resources :prospects
  devise_for :users
root to: "prospects#new"
   namespace :api do
     namespace :v1 do 
       resources :prospects
     end
   end

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
	geocoded_by :location
	after_validation :geocode 
	belongs_to :stage
	belongs_to :user, :class_name => "User", foreign_key: :managed_by
	after_commit :background_jobs
	validates_presence_of :full_name, :location, :phone, :email, :stage_id, :managed_by
	validates_length_of :phone, :in => 7..32
	validates_numericality_of :phone
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
	validates_uniqueness_of :phone, :email , scope: :managed_by

	def background_jobs
		
		StagesWorker.perform_async(self.id)
		mail = Notification.send_email(self.id)
		mail.deliver_later!
	end
end

app/controllers/api/v1/prospects_controller.rb
module Api
	module V1
		class ProspectsController < ApplicationController
			respond_to :json
			
			def index
				pro=Prospect.find(params[:id])
				pro.stage_id=params[:stage_id]
				success= pro.save
				if success
					render json: {success: 'Successfully updated'}, status: :updated
			  else
			    render json: {failed: 'Unsuccessful'}, status: :unprocessable_entity
			  end


			end
		end
	end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = (current_user.role.name=="Sales Manager")? (Prospect.all):(current_user.prospects)
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'Prospect was successfully created.' }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1
  # PATCH/PUT /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: 'Prospect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_params
      params.require(:prospect).permit(:full_name, :email, :phone, :location, :stage_id, :managed_by, :interest_level)
    end
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/prospects/_form.html.erb
<%= form_for(@prospect) do |f| %>
  <% if @prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% @prospect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name ,:required => true%>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email ,:required => true%>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone ,:required => true %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location ,:required => true%>
  </div>
 <div class="form-group">
    <%= f.label :interest_level %><br>
    <%= f.number_field :interest_level ,:required => true%>
  </div>
  <div class="form-group">
    <%= f.label :stage_id %><br>
    <%= f.collection_select(:stage_id, Stage.all, :id, :name, prompt: true) %>
  </div>
 <div class="form-group">
   <%= f.hidden_field :managed_by, :value => current_user.id %>
  </div>
 
  <%= f.submit "Submit" , class: "btn btn-primary" %> or <%= link_to 'Back', prospects_path, class: "btn btn-danger" %>

<% end %>

app/views/prospects/edit.html.erb
<h1>Editing Prospect</h1>

<%= render 'form' %>

app/views/prospects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prospects</h1>

<table class="table table-striped" id="myTable">
  <thead>
    <tr>
      <th>#</th>
      <th>Full name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Location</th>
      <th>Interest Level</th>
      <th>Stage</th>
      <% if current_user.role.name=="Sales Manager" %>
      <th>Managed By</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each_with_index  do |prospect,index| %>
      <tr>
        <td><%= index +1 %></td>
        <td><%= prospect.full_name %></td>
        <td><%= prospect.email %></td>
        <td><%= prospect.phone %></td>
        <td><%= prospect.location %></td>
        <td><%= prospect.interest_level %></td>
        <td><%= prospect.stage.try(:name) %></td>
          <% if current_user.role.name=="Sales Manager" %>
      <td><%= prospect.user.full_name %></td>
      <% end %>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
        <td><%= link_to 'Destroy', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path %> 

<script>
$(document).ready(function(){
    $('#myTable').DataTable();
});
</script>

app/views/prospects/new.html.erb
<h1>New Prospect</h1>

<%= render 'form' %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @prospect.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @prospect.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @prospect.phone %>
</p>

<p>
  <strong>Location:</strong>
  <%= @prospect.location %>
</p>

<p>
  <strong>Interest Level</strong>
  <%= @prospect.interest_level %>
</p>


<p>
  <strong>Stage:</strong>
  <%= @prospect.stage.name %>
</p>

<%= image_tag ("http://image.maps.cit.api.here.com/mia/1.6/mapview?app_id=hmssS2har1wNpfIruxAi&app_code=4UP-uMLiNYaGAKcXOw1XHQ&ci=#{@prospect.location}&h=300&w=600&z=13&f=0&style=alps"), :class =>"map", :width =>"500" %>
</br></br>
<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>