config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  resources :stages
  resources :tasks
  resources :customers
  resources :prospects
  devise_for :users
root to: "prospects#new"
   namespace :api do
     namespace :v1 do 
       resources :prospects
     end
   end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LMS</title>
 
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default navbar-pf" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      </div>
       <% if user_signed_in? %>
       <% if current_user.role.name=="Sales Manager" %>
      <div class="collapse navbar-collapse navbar-collapse-1">

        <ul class="nav navbar-nav navbar-primary">

        <a class="navbar-brand" href="#">
           SALES MANAGER

        </a>

        <% elsif current_user.role.name=="Sales Associate" %>
        <div class="collapse navbar-collapse navbar-collapse-1">

        <ul class="nav navbar-nav navbar-primary">

        <a class="navbar-brand" href="#">
           SALES ASSOCIATE

          
        </a>
        <%end%>
        <%end%>



        <ul class="nav navbar-nav navbar-utility">
        <li class="dropdown">


      </li>

          <li class="dropdown">
              <% if user_signed_in? %>
                  <li><%= link_to "Hello, #{current_user.full_name}", "#" %></li>
                
             </li>
  
  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>


  <%end%>
            </ul>
          </li>


    </ul>
  </div>

      </div>
    </nav>
     <% if user_signed_in? %>
    <div class="col-md-3">
<div class="nav-pf-vertical nav-pf-vertical-with-sub-menus">
  <ul class="list-group">
    <li class="list-group-item">
        <%= link_to "Prospects", prospects_path %>
    </li>
   
    <% if current_user.role.name=="Sales Manager" %>
    <li class="list-group-item">
        <%= link_to "Customers", customers_path %>
    </li>
    <li class="list-group-item">
        <%= link_to "Invite User", new_user_invitation_path %>
    </li>
    <% end %>
    <li class="list-group-item">
        <%= link_to "Tasks", tasks_path %>
    </li>
    <% end %>
  </ul>
</div>
</div>

<div class="container">
 <div class="col-md-9">
  <% if notice %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>

  <% if alert %>
    <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %>

  <%= yield %>
</div>
</div>
</body>
</html>